---
  version: '2'
  
  services:
    zookeeper:
      image: confluentinc/cp-zookeeper:5.1.0
      hostname: zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
  
    kbroker:
      image: confluentinc/cp-enterprise-kafka:5.1.0
      hostname: kbroker
      container_name: kbroker
      depends_on:
        - zookeeper
      ports:
        - "9091:9091"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_BROKER_RACK: DCC
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kbroker:9091
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3
  
    rabbitmq:
      image: rabbitmq:3-management-alpine
      hostname: rabbitmq
      container_name: rabbitmq
      volumes:
        - ./rabbitmq/etc/:/usr/share/rabbitmq/etc/
        - ./rabbitmq/data/:/usr/share/rabbitmq/data/
        - ./rabbitmq/logs/:/usr/share/rabbitmq/logs/
      ports:
        - '15672:15672'
        - '5672:5672'
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin      
  
  
    connect:
      image: confluentinc/cp-kafka-connect:5.1.1
      container_name: connect
      hostname: connect
      depends_on:
        - zookeeper
        - kbroker
        - mssql
      ports:
         - "8083:8083"
         - "9997:9997"
  #	Para agrear nuevos drivers.	   
      volumes:
        - ./plugins/jdbc/:/usr/share/java/kc-jdbc-plugins/
        - ./plugins/gcp/:/usr/share/java/kc-gcp-plugins/
        - ./plugins/trace/:/usr/share/java/kc-trace-plugins/ 
        - ./plugins/jmx/:/usr/share/kc-jmx-plugins/
        - ./plugins/rabbit/:/usr/share/kc-rabbit-plugins/
      environment:
        CONNECT_BOOTSTRAP_SERVERS: 'kbroker:9091'
        CONNECT_REST_ADVERTISED_HOST_NAME: connect
        CONNECT_REST_PORT: 8083
        CONNECT_GROUP_ID: compose-connect-group
        CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
        CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
        CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
        CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
        CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'true'
        CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'true'
        CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        CONNECT_PRODUCER_INTERCEPTOR_CLASSES: ''
        CONNECT_CONSUMER_INTERCEPTOR_CLASSES: ''
        CONNECT_LOG4J_LOGGERS: 'fif.gob.eda.rabbitmq.sink=DEBUG,org.apache.zookeeper=ERROR,com.google.pubsub.kafka=INFO,org.I0Itec.zkclient=ERROR,org.reflections=INFO,io.confluent.connect.jdbc=INFO'
        CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
        CONNECT_PLUGIN_PATH: "/usr/share/kc-rabbit-plugins/, /usr/share/java/kc-jdbc-plugins, /usr/share/java/kc-gcp-plugins, /usr/share/java/kc-trace-plugins "
        GOOGLE_APPLICATION_CREDENTIALS: ''
  #      KAFKA_OPTS: -DJAEGER_SERVICE_NAME="kc-nerdearla" -DJAEGER_AGENT_HOST=jaeger -DJAEGER_AGENT_PORT=6831 -DJAEGER_REPORTER_LOG_SPANS=true -DJAEGER_SAMPLER_TYPE=const -DJAEGER_SAMPLER_PARAM=1      
  #############Monitoreo##############
        KAFKA_JMX_PORT: 9997
        KAFKA_JMX_HOSTNAME: localhost
        KAFKA_JMX_OPTS: -javaagent:/usr/share/kc-jmx-plugins/jmx_prometheus_javaagent-0.3.1.jar=7070:/usr/share/kc-jmx-plugins/metrics.yaml -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9997

    mssql:
        image: microsoft/mssql-server-linux:2017-latest
        hostname: mssql
        container_name: mssql
        ports:
          - "1433:1433"
        environment:
          SA_PASSWORD: "Falabella.2019!"
          ACCEPT_EULA: "Y"      
  